splash = false

preload = /home/infinit3i/wallpapers/*

monitor=DP-3
monitor=DP-4
monitor=HDMI-A-5

# Preload images
preload = /home/infinit3i/wallpapers/swirls.jpg
preload = /home/infinit3i/wallpapers/swirls2.jpg
preload = /home/infinit3i/wallpapers/swirls3.jpg

# Assign wallpapers to monitors
wallpaper = DP-3,/home/infinit3i/wallpapers/swirls.jpg
wallpaper = DP-4,/home/infinit3i/wallpapers/swirls2.jpg
wallpaper = HDMI-A-5,/home/infinit3i/wallpapers/swirls3.jpg

# Optional (recommended)
splash = false
