splash=false

wallpaper {
  monitor=DP-3
  path=/home/infinit3i/wallpapers/swirls2.jpg
}

wallpaper {
  monitor=DP-4
  path=/home/infinit3i/wallpapers/swirls.jpg
}

wallpaper {
  monitor=HDMI-A-5
  path=/home/infinit3i/wallpapers/swirls3.jpg
}
