general {
  lock_cmd = pkill hyprsunset; hyprlock
  before_sleep_cmd = pkill hyprsunset; hyprlock
  ignore_dbus_inhibit = false
}

listener {
  timeout = 540
  on-timeout = hyprsunset -g 40
  on-resume = pkill hyprsunset
}

listener {
  timeout = 600
  on-timeout = hyprlock
}

listener {
  timeout = 900
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}
