# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = 
$applauncher = rofi
$terminal = alacritty
$idlehandler = swayidle -w timeout 300 'pidof hyprlock >/dev/null || hyprlock --immediate' before-sleep 'pidof hyprlock >/dev/null || hyprlock --immediate'

# Screenshots
$shot-region = sh -c 'file=~/Pictures/screenshots/screenshot_$(date +%F_%T).png; grim -g "$(slurp)" - | tee "$file" | wl-copy; notify-send "Screenshot saved" "$file"'
$shot-window = sh -c 'file=~/Pictures/screenshots/screenshot_$(date +%F_%T).png; grim -g "$(hyprctl -j activewindow | jq -r \"\\\"\\(.at[0]),\\(.at[1]) \\(.size[0])x\\(.size[1])\\\"\")" - | tee "$file" | wl-copy; notify-send "Screenshot saved" "$file"'
$shot-screen = sh -c 'file=~/Pictures/screenshots/screenshot_$(date +%F_%T).png; grim - | tee "$file" | wl-copy; notify-send "Screenshot saved" "$file"'